### ISSUE TITLE
ADS crate

### ISSUE THREAD

**Issue by windelbouwman** [birkenfeld/ads-rs#1]
Hi!

Recently discovered you crate, and also did some experiments with a rust implementation of ADS.

https://github.com/windelbouwman/lognplot/tree/master/rads

Any chance you still doing something with this? I do not have access to a PLC, so I cannot test my code, but the protocol of ADS appeared simple enough to implement.

Regards,
Windel

**Comment by birkenfeld** [comment]
Hi!  You're correct that the protocol is not very complicated.  I realize the crate looks dead, but I definitely intend to work on this topic at some point.  I wanted the crate to be async, but at the time I started it, the whole async story hadn't really taken off yet.  Now might be better, but I'll have to find some time for it again...
