### ISSUE TITLE
Unable to set TC status

### ISSUE THREAD

**Issue by gimmi** [birkenfeld/ads-rs#17]
Hello, 

I am trying to use the `adstool` example to set device status, but I am unable to do it.

The same operation works fine using the TwinCAT Powershell API

![image](https://user-images.githubusercontent.com/6589/236479752-2111b9ad-4a68-43d5-849b-151f330e8bd4.png)

**Comment by birkenfeld** [comment]
Also, there is `Reconfig` which must apparently be used to set to config mode, instead of `Config`.

**Comment by gimmi** [comment]
Interesting, will try later

**Comment by gimmi** [comment]
Confirm working, here is the full test

Starting from state `Config`

```
C:\temp>adstool.exe 127.0.0.1/192.168.15.4.1.1 state
Device: TwinCAT System 3.1.4024
Current state: Config
```

Go from `Config` to `Run`

```
C:\temp>adstool.exe 127.0.0.1/192.168.15.4.1.1 state Reset
Device: TwinCAT System 3.1.4024
Current state: Config
Set new state: Reset
```

Go from `Run` to `Run` (restart)

```
C:\temp>adstool.exe 127.0.0.1/192.168.15.4.1.1 state Reset
Device: TwinCAT System 3.1.4024
Current state: Run
Set new state: Reset
```

Go from `Run` to `Config`

```
C:\temp>adstool.exe 127.0.0.1/192.168.15.4.1.1 state Reconfig
Device: TwinCAT System 3.1.4024
Current state: Run
Set new state: Reconfig
```

Go from `Config` to `Config`

```
C:\temp>adstool.exe 127.0.0.1/192.168.15.4.1.1 state Reconfig
Device: TwinCAT System 3.1.4024
Current state: Config
Set new state: Reconfig
```

**Comment by birkenfeld** [comment]
Great! I'll add some text to the help of the `state` command, but I don't want to change the behavior as long as I don't have full knowledge of what Beckhoff are doing, and I don't think it's documented. Ok?

**Comment by gimmi** [comment]
absolutely, I think your driver is doing the right thing by exposing ADS api as is, then the fact that ADS protocol has strange quirks here and there is something that need to be handled by the application code
