### ISSUE TITLE
silent panic if twincat restarts mid-read

### ISSUE THREAD

**Issue by chammel4** [birkenfeld/ads-rs#18]
I'm finding that if a twincat restart completes (not sure yet exactly at which state transition the problem occurs) during device.get_state() or ads::Handle.read(), or ads::Handle::new(), the call never returns with a Result<> - this leads me to believe something in the background silently panics.

Is there something you're aware of that can be monitored to explicitly avoid this scenario? or otherwise, suggestions for where this silent panic may be taking place?

Thanks!

**Comment by birkenfeld** [comment]
Are you creating the client with `Timeouts::none()`? It is recommended to use a timeout to avoid this.

**Comment by chammel4** [comment]
good call, kind sir! That took care of it - now nicely riding through TC restarts.  I didn't realize I had used Timeouts::none

**Comment by chammel4** [comment]
nothing to be done - Timeouts::none was erroneously used
