### ISSUE TITLE
Further Symbol and Type data

### ISSUE THREAD

**Issue by Krystian-L-Lis** [birkenfeld/ads-rs#21]
Is there any way to decode further Symbols and Type data? You mentioned in the source code that some properties were jumped over. Is there any documentation on that?

**Comment by birkenfeld** [comment]
IIRC, the details in the source code come from Beckhoff's header files that are shipped with their Twincat ADS lib, but there is no official documentation. What data are you interested in?

**Comment by birkenfeld** [comment]
Closing due to lack of feedback.
