### ISSUE TITLE
Reading multiple handles

### ISSUE THREAD

**Issue by divi255** [birkenfeld/ads-rs#5]
Good day,

First, great library! Missing async support but I read the previous issues and understand why. Hope to help you with that soon.

About the subject - as I see there's no crate method to read multiple variables by their handles, can you please at least make Handle::handle public or create a getter for it?

**Comment by birkenfeld** [comment]
Sure - added `Handle::raw` now.

How do you read multiple handles - using a sum-up request?

**Comment by divi255** [comment]
Yep. Actually I moved everything to sum-ups, but having public methods in handle is good for testing anyway
